spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}

  flyway:
    schemas: chickendb
    create-schemas: true
    url: jdbc:mariadb://localhost:3307/
    user: root
    password: geheim
  datasource:
    url: jdbc:mariadb://localhost:3307/chickendb
    username: root
    password: geheim

Chicken:
  rollen:
    orga:
    tutor:
