CREATE TABLE IF NOT EXISTS
    KLAUSUR (
                LSF_ID INTEGER PRIMARY KEY NOT NULL ,
                NAME VARCHAR(100) NOT NULL,
                PRAESENZ BOOLEAN NOT NULL,
                DATUM DATE NOT NULL,
                BEGINN TIME NOT NULL,
                ENDE TIME NOT NULL

);

CREATE TABLE IF NOT EXISTS
    STUDENT (
                STUDENT_ID INTEGER PRIMARY KEY,
                RESTURLAUB INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS
    URLAUB (

               ID INTEGER PRIMARY KEY AUTO_INCREMENT,
               STUDENT_DTO INTEGER,
               TAG DATE NOT NULL,
               BEGINN TIME NOT NULL,
               ENDE TIME NOT NULL,
               FOREIGN KEY (STUDENT_DTO) REFERENCES STUDENT(STUDENT_ID)
);

CREATE TABLE IF NOT EXISTS
    KLAUSUR_STUDENT (
                        KLAUSUR INTEGER NOT NULL,
                        STUDENT_DTO INTEGER NOT NULL ,
                        PRIMARY KEY (KLAUSUR,STUDENT_DTO)
);

