name: Run Gradle on PRs
on: [push, pull_request]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
              name: Git Checkout
            - name: Java installieren
              uses: actions/setup-java@v3
              with:
                java-version: 17
                distribution: 'temurin'
            - name: Run Gradle
              run: ./gradlew test
