name: Run Gradle on PRs
on: [push, pull_request]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Java installieren
              uses: actions/setup-java@v1
              with:
                java-version: 17
            - name: Run Gradle Tests
              run: ./gradlew test
